name: retro_eshop
description: "R-Shop â€” A retro game manager for Android with a console-style UI, controller support, and download queue."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: 2.6.1
  flutter_soloud: 2.1.7
  dio: 5.9.1
  html: 0.15.6
  path_provider: 2.1.5
  permission_handler: 11.4.0
  shared_preferences: 2.5.4
  flutter_secure_storage: 9.2.4
  file_picker: 8.3.7
  google_fonts: 6.3.3
  sqflite: 2.4.2
  path: 1.9.1
  cached_network_image: 3.4.1
  flutter_cache_manager: 3.4.1
  smb_connect: 0.0.9
  ftpconnect: 2.0.10
  share_plus: 10.1.4
  flutter_foreground_task: 9.2.0
  image: 4.3.0
  crypto: 3.0.7
  url_launcher: 6.3.2
  confetti: 0.8.0
  package_info_plus: 8.3.1
  flutter_svg: 2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: 1.3.3
  sqflite_common_ffi: 2.4.0+2
  flutter_lints: 6.0.0
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.4.4
  path_provider_platform_interface: 2.1.2
  plugin_platform_interface: 2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/icon.png
    - assets/platform_icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#121212"
  image: "assets/icon.png"
  fullscreen: true
